server:
  port: 8100

spring:
  application:
    name: user-service

  datasource:
    url: ${UMS_DB_URL:jdbc:postgresql://localhost:55432/identity_db}
    username: ${UMS_DB_USERNAME:postgres}
    password: ${UMS_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AS_ISSUER_URI:http://localhost:9090}
          jwk-set-uri: ${AS_JWK_SET_URI:http://localhost:9090/oauth2/jwks}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://tempo-service:4318/v1/traces}
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.examplatform.identity: INFO

