server:
  port: 9000

spring:
  application:
    name: authorization-server
  datasource:
    url: ${OAUTH_DB_URL:jdbc:postgresql://localhost:55432/identity_db}
    username: ${OAUTH_DB_USERNAME:postgres}
    password: ${OAUTH_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 20000
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: "0"
    locations: classpath:db/migration
    out-of-order: true
  sql:
    init:
      mode: never

app:
  auth:
    issuer: ${AS_ISSUER_URI:http://localhost:9090}
    cors:
      allowed-origins: ${AS_ALLOWED_ORIGINS:http://localhost:5173}
    bff-client:
      client-id: ${BFF_CLIENT_ID:exam-bff-client}
      client-secret: ${BFF_CLIENT_SECRET:exam-bff-secret}
      redirect-uri: ${BFF_REDIRECT_URI:http://localhost:8080/login/oauth2/code/exam-oidc}
    spa-client:
      client-id: ${SPA_CLIENT_ID:react-test-client}
      redirect-uri: ${SPA_REDIRECT_URI:http://localhost:5173/auth/callback}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://tempo-service:4318/v1/traces}
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.example.authserver: DEBUG


