apiVersion: v1
kind: ServiceAccount
metadata:
  name: bff-gateway
  namespace: exam-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-service
  namespace: exam-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-server
  namespace: exam-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: session-service
  namespace: exam-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-service
  namespace: exam-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: exam-platform
